### ISSUE TITLE
Occasional exception when clicking a button also changes its prompt.

### ISSUE THREAD

**Issue by greydust** [BoltManGuy/MHR-InGame-ModMenu-API#10]
![image](https://user-images.githubusercontent.com/7523684/183785979-bc06c589-e133-4607-a105-cbe87597c364.png)

When a user clicks/hits the "Gamepad Trigger" button, the prompt will become "Press trigger" and the mod would try to get the next button the user presses and write it into the prompt field. However, occasionally this would throw the exception in the image and stop the prompt from updating. The other parts (getting the next button and setting up the trigger button) still works.

Code: https://github.com/greydust/mhrise-falbg/blob/f8bcf3d717d422258a31879f10d9925e665a5132/src/reframework/autorun/falbg/native_ui.lua#L19

**Comment by Bolt-Scripts** [comment]
Seems odd, do you have any more info on how to replicate this, because I wasn't able to make it happen in my few minutes of testing your script.

**Comment by greydust** [comment]
I can't make it happen today, either. I think I'll close the issue.
