### ISSUE TITLE
[Bug] Crash when trying to hide elements with a button

### ISSUE THREAD

**Issue by GreenComfyTea** [BoltManGuy/MHR-InGame-ModMenu-API#4]
**Describe the bug**
The game crashes when I show elements with a button, then scroll (with a gamepad) to the last element in the menu, then go up and try to hide elements with said button.

**Video**
[https://imgur.com/a/nYBq8dv](https://imgur.com/a/nYBq8dv)

**Comment by Bolt-Scripts** [comment]
I feeeel like this is gonna simply be another dumb cursor issue, IIRC the game crashes if the cursor is set to an element that is outside the bound of the list and such, so when you try hide them, I imagine the scroll bar is being set past the maximum or something trying to maintain the same scroll amount while the amount of items has changed.
But man it's so annoying there's no protections for any of this in the game and it just crashes if you do something even slightly off. Like why couldn't they just be nice programmers and clamp the values for cases like this.

**Comment by Bolt-Scripts** [comment]
should be fixed now 461578679056b138d6916f15ea4f710be8622dd5
