### ISSUE TITLE
[Feature Suggestion] Fit text in tooltips

### ISSUE THREAD

**Issue by raff-run** [BoltManGuy/MHR-InGame-ModMenu-API#7]
Hey! When I was implementing my mod options with your API, I noticed that the text will resize and become unreadable if too lengthy.
This means that it needs carefully applied newlines, and also that the newlines need to be at different places if you're also using the usual REF UI since they have different default window sizes.

So I made a lua util function that automatically finds the best way to fit a text in a tooltip and caches the result, and wanted to share it with you if you in case want to incorporate it into the mod's API:

```lua
local minLineLength = 40
local lineBreakPattern = "(" .. ('.'):rep(minLineLength) .. ('.?'):rep(16) .. ") "  -- in regex: /(.{40,56}) /
local conversionCache = {} -- the UI will slow down without a cache

local function wrapText(text)
    text = text:gsub("\n", " "):gsub("  ", " ") -- this is here just so authors can feed their REF ui label strings straight into the api instead of having a version for each
    text = text:gsub(lineBreakPattern, "%1\n")
    return text
end

local function fitInBox(text)
    local newText = conversionCache[text]
    if newText ~= nil then return newText end

    newText = wrapText(text)
    conversionCache[text] = newText

    return newText
end

local function fitOptionsInBox(textTable)
    local newTextTable = conversionCache[textTable]
    if newTextTable ~= nil then return newTextTable end
    newTextTable = {}

    for _, text in ipairs(textTable) do
        table.insert(newTextTable, wrapText(text)) 
    end

    conversionCache[textTable] = newTextTable

    return newTextTable
end
```

Here are some example outputs:
![image](https://user-images.githubusercontent.com/44688128/183278973-53cdcbe6-eace-402b-91e8-a3ddb86bc618.png)
![image](https://user-images.githubusercontent.com/44688128/183278977-0fbb42a3-a71a-4c80-b9c6-e76590f1ecf3.png)
![image](https://user-images.githubusercontent.com/44688128/183278987-4f2e70e0-8f5c-4d7c-8fa1-fdd8fe6c6814.png)
![image](https://user-images.githubusercontent.com/44688128/183279022-520368ef-4d09-431b-8669-36d1a405e5e8.png)

Of course, if the string is long enough, it will overflow downwards, but I think that's better than seeing this and then having to place line breaks yourself:
![image](https://user-images.githubusercontent.com/44688128/183279102-3a9c2d59-f9e7-4f79-bff8-86a07166125b.png)

**Comment by Bolt-Scripts** [comment]
Neato. Was wondering if someone would bother to do something like this.
I think you should make a PR to implement this.
Though you shouldn't need the cache thing since they should basically be cached in the option data itself already.
Should just need to look around the ModMenuApi.lua line 140:
`displayMessage = toolTip;`
and send the tooltip through the function and assign to the display message and bingo
If you really don't wanna bother though, I can implement it.

**Comment by raff-run** [comment]
Sure! I'll give it a try.
